### ISSUE TITLE
Shadowing same name outputs on group actor

### ISSUE THREAD

**Issue by artmello** [leapp-to/snactor#58]
On current implementation each actor returns JSON data based on the specified JSL schema. Content of such JSON is based on keys named as outputs by actor definition. If two actors define the same name for their outputs and a group actor try to execute both we are not able to retrieve all two of them since one will shadow the other. Example:

actor01/_actor.yaml:
```
outputs:
  name: message
  type:
    name: Message
  execute:
    executable: /usr/bin/python
    script-file: actor01.py
```
actor02/_actor.yaml:
```
outputs:
  name: message
  type:
    name: Message
  execute:
    executable: /usr/bin/python
    script-file: actor02.py
```
group/_actor.yaml:
```
outputs:
- name: message
  type:
    name: Message
- name: message
  type:
    name: Message
group:
- actor01
- actor02
```
will output:
```
$ snactor_runner --actors_dir=./sample/actors/ --schemas_dir=./sample/schemas/ --validate group
{"message": {"value": "Sample Actor 02"}}
```
Such example is not a good naming pattern for real code, but as soon as we start to have more actors things like, return_code, rc or result can happen more frequently. Maybe snactor could encapsulate every actor output inside some JSON key like $ACTOR_NAME?
